[package]
name = "wgpu_matrix_multiplication"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "23.0.1"
bytemuck = { version = "1.21", features = ["derive"] }
tokio = { version = "1.42.0", features = ["full"] }
flume = "0.11"
